# Generated by Django 5.2.3 on 2025-06-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, help_text='Tell us about yourself (500 characters max)', max_length=500, null=True, verbose_name='Biography'),
        ),
    ]
