# Generated by Django 5.2.3 on 2025-07-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_city_profile_country_profile_geo_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='account_type',
            field=models.CharField(choices=[('volunteer', 'Volunteer'), ('manager', 'Manager')], default='volunteer', max_length=100, verbose_name='Account type'),
        ),
    ]
