# Generated by Django 5.2.3 on 2025-08-20 09:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_account_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UpgradeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Status')),
                ('motivation', models.TextField(help_text='Share how you plan to support the community if your request is approved', verbose_name='Motivation')),
                ('request_datetime', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Request Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgrade_requests', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Upgrade Request',
                'verbose_name_plural': 'Upgrade Requests',
            },
        ),
        migrations.CreateModel(
            name='UpgradeRequestReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject')], max_length=7, verbose_name='Vote')),
                ('note', models.TextField(blank=True, help_text='Leave a note for that volunteer as a feedback.', null=True, verbose_name='Note')),
                ('date_reviewed', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Reviewed')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upgrade_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Manager')),
                ('upgrade_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='users.upgraderequest', verbose_name='Upgrade Request')),
            ],
            options={
                'verbose_name': 'Upgrade Request Review',
                'verbose_name_plural': 'Upgrade Request Reviews',
                'unique_together': {('upgrade_request', 'manager')},
            },
        ),
    ]
