# Generated by Django 5.2.3 on 2025-07-18 23:16

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_alter_profile_account_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20, verbose_name='Status')),
                ('info', models.TextField(blank=True, help_text='Additional information about the intiative like requests or notes.', verbose_name='Information')),
                ('geo_location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Geolocation')),
                ('required_volunteers', models.PositiveIntegerField(verbose_name='Required volunteers')),
                ('scheduled_datetime', models.DateTimeField(help_text='When is the initiative is going to start', verbose_name='Scheduled date and time')),
                ('duration_days', models.PositiveIntegerField(default=1, help_text='Number of days the initiative will last', verbose_name='Duration (days)')),
                ('end_datetime', models.DateTimeField(blank=True, help_text='When the initiative ends', null=True, verbose_name='End date and time')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date created')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.city', verbose_name='City')),
                ('volunteers', models.ManyToManyField(blank=True, related_name='initiatives_joined', to=settings.AUTH_USER_MODEL, verbose_name='Volunteers')),
            ],
            options={
                'verbose_name': 'Initiative',
                'verbose_name_plural': 'Initiatives',
            },
        ),
    ]
