# Generated by Django 5.2.3 on 2025-07-18 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('users', '0006_alter_profile_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.city', verbose_name='City'),
        ),
    ]
