# Generated by Django 5.2.3 on 2025-07-21 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initiative_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='status',
            field=models.CharField(choices=[('under_review', 'Under Review'), ('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('review_failed', 'Review Failed'), ('cancelled', 'Cancelled')], default='under_review', max_length=20, verbose_name='Status'),
        ),
    ]
