# Generated by Django 5.2.3 on 2025-07-24 10:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_initiative_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InitiativeReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject')], max_length=7, verbose_name='Vote')),
                ('date_reviewed', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Reviewed')),
                ('initiative', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='core.initiative', verbose_name='Initiative')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiative_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Manager')),
            ],
            options={
                'unique_together': {('initiative', 'manager')},
            },
        ),
    ]
