# Generated by Django 5.2.3 on 2025-07-24 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_initiativereview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='initiativereview',
            options={'verbose_name': 'Initiative Review', 'verbose_name_plural': 'Initiatives Reviews'},
        ),
    ]
