# Generated by Django 5.2.3 on 2025-07-31 23:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_alter_initiativereview_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('initiative_created', 'Initiative Created'), ('initiative_approved', 'Initiative Approved'), ('initiative_review_failed', 'Initiative Review Failed'), ('initiative_started', 'Initiative Started'), ('initiative_cancelled', 'Initiative Cancelled'), ('initiative_completed', 'Initiative Completed'), ('announcement', 'Announcement')], max_length=50, verbose_name='Notification type')),
                ('message', models.TextField(verbose_name='Message')),
                ('is_broadcast', models.BooleanField(default=False, help_text='If set to True the notification will be to all users.', verbose_name='Is broadcast')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is read')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('recipients', models.ManyToManyField(blank=True, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Recipients')),
                ('related_initiative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.initiative', verbose_name='Related initiative')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
