# Generated by Django 5.2.3 on 2025-08-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('initiative_created', 'Initiative Created'), ('initiative_approved', 'Initiative Approved'), ('initiative_review_failed', 'Initiative Review Failed'), ('initiative_started', 'Initiative Started'), ('initiative_cancelled', 'Initiative Cancelled'), ('initiative_completed', 'Initiative Completed'), ('announcement', 'Announcement'), ('upgrade_request_created', 'Upgrade Request Created')], max_length=50, verbose_name='Notification type'),
        ),
    ]
