# Generated by Django 5.2.3 on 2025-08-23 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_notification_type'),
        ('users', '0007_upgraderequest_upgraderequestreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_upgrade_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='users.upgraderequest', verbose_name='Related upgrade request'),
        ),
    ]
