# Generated by Django 5.2.3 on 2025-09-17 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('notifications', '0003_notification_related_upgrade_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='related_initiative',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='related_upgrade_request',
        ),
        migrations.AddField(
            model_name='notification',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='notification',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_broadcast',
            field=models.BooleanField(default=False, help_text='If set to True the notification will be sent to all users.', verbose_name='Is broadcast'),
        ),
    ]
